version: ‘3.8’
services:
  frontend:
    image: frontend:latest
    ports:
      - “3000:3000”
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000  # URL of the Flask backend service
  backend:
    image: backend:latest
    ports:
      - “5000:5000"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=databasemysql
      - MYSQL_DB=Buckymon_Go_DB
  mysql:
    image: database_docker_img:latest
    ports:
      - “3306:3306”
    environment:
      - MYSQL_ROOT_PASSWORD=databasemysql
      - MYSQL_DATABASE=Buckymon_Go_DB