services:
  gitlab-runner:
    build:
      context:
      dockerfile: runner.dockerfile
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - /srv/gitlab-runner/builds:/builds