# Use latest MySQL image from Docker Hub
FROM mysql:latest

# Setting up the environment variables
ENV MYSQL_ROOT_PASSWORD=ShXoPIL7d*%


# Copy the DB setup and test scripts into the container
COPY db_setup.sql db_test.sql clean_db.sql /docker-entrypoint-initdb.d/